# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        app:
            index_name: app_%kernel.environment%
            types:
                users:
                    properties:
                        id: { type: integer }
                        username: { type: text }
                        email: { type: text }
                        enabled: { type: boolean }
                        salt: { type: text }
                        lastLogin: { type: date, format: basic_date_time }
                        confirmationToken: { type: text }
                        roles:
                            type: text
#                            properties:
#                                id: { type: integer }
#                                name: { type: text }
                    persistence:
                        # the driver can be orm, mongodb or phpcr
                        driver: orm
                        model: App\Entity\User
                        provider: ~
                        finder: ~
